name: Daily Build

on:
  schedule:
    - cron: '0 2 * * *'  # 这表示每天凌晨2点触发workflow，你可以根据需要调整时间

jobs:
  build:
    runs-on: ubuntu-latest  # 选择运行环境，这里选择的是最新的Ubuntu系统
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 使用GitHub提供的action来检出代码

      - name: Set up Python
        uses: actions/setup-python@v3  # 设置Python环境
        with:
          python-version: 3.9  # 选择Python版本，你可以根据需要调整

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 安装项目依赖

      - name: Build project  # 这一步是示例，你需要根据项目的实际情况来编写打包命令
        run: |
          # 假设你的项目是一个Python包，你可以使用下面的命令来打包
          python setup.py sdist bdist_wheel

      - name: Upload artifact  # 上传打包结果作为workflow的artifact，方便后续下载和查看
        uses: actions/upload-artifact@v3
        with:
          name: project-package
          path: dist/  # 假设打包结果放在dist目录下，你需要根据实际情况调整